using AuctionSniper.Domain;

namespace AuctionSniper.UI.Wpf
{
    public partial class SniperWindow
    {
        public SniperWindow(SnipersTableModel model)
        {
            InitializeComponent();

            grid.ItemsSource = model.DefaultView;
            grid.AutoGeneratedColumns += (sender, args) =>
                {
                    grid.Columns[0].Header = SnipersTableModel.TextFor(SnipersTableModel.Column.ItemIdentifier);
                    grid.Columns[1].Header = SnipersTableModel.TextFor(SnipersTableModel.Column.LastPrice);
                    grid.Columns[2].Header = SnipersTableModel.TextFor(SnipersTableModel.Column.LastBid);
                    grid.Columns[3].Header = SnipersTableModel.TextFor(SnipersTableModel.Column.SniperState);
                };
        }
    }
}
